### ISSUE TITLE
Support for Custom Scalar Types

### ISSUE THREAD

**Issue by topbloc-beiswenger** [kloeckner-i/ember-cli-mirage-graphql#19]
It would be great to have support for custom scalar types like JSON, UUID, DateTime, etc. Currently, when testing, I get the following error which breaks the mock for whatever query object types have a custom scalar `GraphQL error: No mock defined for type "UUID"`.

**Comment by jneurock** [comment]
Thanks for opening this. Could you provide some example code so I can add a test?

**Comment by topbloc-beiswenger** [comment]
After adding custom scalar types in the dummy app, they seem to be working fine. I'm going to have to dive into this library a little more to figure out what's going on behind the scenes.

**Comment by jneurock** [comment]
Ok. Let me know if/how I can help.

**Comment by jneurock** [comment]
This should be closed by #32
