### ISSUE TITLE
Cannot query non-null list of non-null objects 

### ISSUE THREAD

**Issue by dmzza** [kloeckner-i/ember-cli-mirage-graphql#29]
If my schema defines a Query like this:

```GraphQL
# app/graphql/schema.graphql
type Query {
  designs(skip: Int, after: ID, before: ID, first: Int, last: Int): [Design!]!
}
```

### Expected Behavior
Querying for `designs` should return a non-null list of non-null `Design` objects.

### Actual Behavior
I get this error:

```Javascript 
[Error] TypeError: undefined is not an object (evaluating 'type._fields[fieldName]')
getFieldType — index.js:16 // This is referring to /addon/fields/selection/index.js
selectedFieldsReducer — index.js:27
reduce
(anonymous function) — index.js:42
(anonymous function) — create.js:15
(anonymous function) — create.js:35
(anonymous function) — query.js:29
(anonymous function)
mockResolver
resolveFieldValueOrError
resolveField
executeFields
executeOperation
executeImpl
(anonymous function)
initializePromise
Promise
graphql
_getMirageResponseForRequest

// ... uninteresting parts of the stack trace omitted ...

(anonymous function) — apollo.js:305
initializePromise — rsvp.js:520
Promise — rsvp.js:1021
query — apollo.js:304

// ... uninteresting parts of the stack trace omitted ...
```

### Fixing ember-cli-mirage-graphql
I noticed that `type._fields` on line 16 of `/addon/fields/selection/index.js` was undefined because `type` was a `GraphQLList` that would need to be "unwrapped". So I wrote a new function to unwrap lists:
```javascript
// /addon/utils.js
export const unwrapList = (type) => type instanceof GraphQLList ? type.ofType : type
```
And then I changed line 12 of `/addon/fields/selection/index.js`:
```diff
-  type = unwrapNonNull(type);
+  type = unwrapNonNull(unwrapList(type));
```
This solved the original error, but then a new error came up:
```
 GraphQL error: Expected Iterable, but did not find one for field Query.designs
```
I struggled to find where this error came from or why it happened. So I gave up on trying to fix ember-cli-mirage-graphql. 😖 

### Changing my schema
I knew that this error started happening when my schema changed, so I isolated the problem to this change:
```diff
- designs(skip: Int, after: ID, before: ID, first: Int, last: Int): [Design!]
+ designs(skip: Int, after: ID, before: ID, first: Int, last: Int): [Design!]!
```
My other queries had the same change, and the same error. I'm just focusing on this one for clarity.

So **I reverted that change** by taking off the last `!` so that now the query returns `[Design!]` and the error is gone. 😌 

I suppose this is a fine workaround for now, but I'm using [Prisma Framework](https://github.com/prisma/prisma2) to generate my GraphQL server and [graphql-cli](https://github.com/Urigo/graphql-cli) version 3.0.14 to generate my `schema.graphql`, so I don't really have control over what it creates. I don't know why this `!` was recently added, but since it appears to be valid GraphQL schema syntax, and my app works if I connect directly to by backend instead of Mirage, then I think ember-cli-mirage-graphql should support this.

**Comment by jneurock** [comment]
Thanks for reporting the issue. I'll see if I can figure out how to work with this use case.

**Comment by louim** [comment]
Hey!
I encountered the same problem, with a slightly different error, but the same stacktrace:
```
index.js:89 TypeError: Cannot read property 'id' of undefined
    at getFieldType (index.js:15)
    at selectedFieldsReducer (index.js:26)
    at utils.js:41
    at Array.reduce (<anonymous>)
    at index.js:41
    at create.js:15
    at create.js:35
    at query.js:29
    at Object.productCurrencyRatios (utils.js:41)
    at eval (mock.js:105)
```
Schema looks like this:
```graphql
type Query {
  """
  Returns a list of product currency ratios
  """
  productCurrencyRatios: [ProductCurrencyRatio!]!
}
```
As it was my first time using this addon, I thought I had configured something wrong before finding this issue.

**Comment by dmzza** [comment]
I know this is super late, but I confirmed that #31 fixed this issue for me. Thank you @jneurock 🙇

**Comment by jneurock** [comment]
Oh hey, glad to hear that! You're welcome; though, I just merged code from @louim :)
