### ISSUE TITLE
Mutations don't update the model

### ISSUE THREAD

**Issue by dmzza** [kloeckner-i/ember-cli-mirage-graphql#36]
Mutations successfully change Mirage's in-browser database, but those changes aren't immediately reflected in the ember app. When you inspect the Mirage request/response, you will see that the mutation responds with `Hello World` for the last name.

## Steps to reproduce
1. Create a default scenario that generates a list of `person`
2. Run the dummy app 
```
$ ember s 
```
3. Go to http://localhost:4200/person/1/edit
4. Edit the last name
5. Save
6. Go to http://localhost:4200/person/1 (this is tricky without having a `<LinkTo>` on the edit page that goes there)

### Actual Result
7. The last name is unchanged
8. If you go to http://localhost:4200/people then you will see the updated last name, because that route needs to preform a new query to get all the People. 

### Expected Result
7. The last name should be updated.

**Comment by 0xadada** [comment]
I'm also seeing 'Hello World'.

**Comment by jneurock** [comment]
Sorry for the late response on this one...

I think the issue in the dummy app's mutation is that it's returning the wrong thing. I will see if I can fix this soon.

Question: Is the dummy app mutation example an important source of information? If so, I think 2 things:
1. The example should work as expect.
2. The valuable information from the dummy app mutation should be promoted to the README.

**Comment by dmzza** [comment]
It isn't so much that the dummy app is an important source of information. But when I ran into this problem in my own app, I used the dummy app as a reference to see what I might have been doing differently that caused the problem. When I realized that the dummy app had the same problem as my app, I came up with a workaround.

**Comment by jneurock** [comment]
Ah, I see. In #39 I fixed the problem. Maybe these changes can help you?
