### ISSUE TITLE
Merging schemas

### ISSUE THREAD

**Issue by knownasilya** [kloeckner-i/ember-cli-mirage-graphql#48]
Getting: `"typeDefs must be a string, array or schema AST, got object"`

With code:

```ts
import createGraphQLHandler from 'ember-cli-mirage-graphql/handler';
import { mergeSchemas } from 'graphql-tools';
import gql from 'graphql-tag';
import coverageSchema from './schema.graphql';

const apiSchema = gql`
  type Vehicle {
    name: String
  }

  type Query {
    vehicles: [Vehicle]
  }
`;

const schema = mergeSchemas({
  schemas: [coverageSchema, apiSchema],
});

export default createGraphQLHandler(schema);
```

Seems to be getting caught up on

<img width="715" alt="Screen Shot 2020-06-01 at 5 53 08 PM" src="https://user-images.githubusercontent.com/34726/83458630-ce9cf600-a430-11ea-9df9-76a6cf679479.png">

**Comment by knownasilya** [comment]
The issue might actually be the query from Apollo, which is converted to Jason by ember Apollo client.

**Comment by knownasilya** [comment]
`requestBody` is `"{"operationName":"Vehicles","variables":{},"query":"query Vehicles {\n  vehicles {\n    name\n    __typename\n  }\n}\n"}"`

**Comment by jneurock** [comment]
For this case, we can change the code so it will accept a raw schema string or, as you've shared, an actual instance of `GraphQLSchema`. Thanks for reporting the issue and providing a sample case!!!
