### ISSUE TITLE
Deprecate in favor of @miragejs/graphql?

### ISSUE THREAD

**Issue by jelhan** [kloeckner-i/ember-cli-mirage-graphql#68]
I'm wondering if this library should be deprecated in favor of [@miragejs/graphql](https://github.com/miragejs/graphql). From the documentation of `@miragejs/graphql`:

> As Mirage itself evolved from an Ember add-on (ember-cli-mirage) so too did Mirage GraphQL (ember-cli-mirage-graphql).

Additionally it lists some advantages of `@miragejs/graphql` over `ember-cli-mirage-graphql`. Please see here for reference: https://github.com/miragejs/graphql#history

Are there still good reasons to use `ember-cli-mirage-graphql`?

**Comment by jneurock** [comment]
It definitely should. I created both of them but I don't think I have access to this repo anymore. I will gladly check with someone who stills has ownership. Sorry we didn't get to that sooner, in case there was any confusion.
