### ISSUE TITLE
Exclude from production builds

### ISSUE THREAD

**Issue by chadian** [kloeckner-i/ember-cli-mirage-graphql#7]
`ember-cli-mirage-graphql` is included in production builds.

## Reproduction steps:
1. `ember build -prod`
2. `grep -ir "ember-cli-mirage-graphql" dist`

Even if it doesn't create any runtime issues it would be useful to keep build sizes down.

**Comment by jneurock** [comment]
Thanks, Chad. This should be done, or at least attempted. At the very least, the README should clearly emphasize how an Ember app should exclude this addon from its production build.
